blank_issues_enabled: false
contact_links:
  - name: Pobierz najnowszą wersję
    url: https://github.com/Torvinek/PlusX-Mobile/releases/latest
    about: Przed zgłoszeniem problemu sprawdź aktualne wydanie aplikacji.
